### Config about Generic
config.not_apply=N/A

### Config about Logs
config.log_msg_base_ok=[OK] » 
config.log_msg_base_info=[INFO] » 
config.log_msg_base_error=[ERROR] » 
config.log_msg_base_request=[REQ] »

### Config about Constants
config.format_datetime_backend=yyyy-MM-dd'T'HH:mm:ss
config.format_timestamp_backend=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
