### Config Rest
spring.application.name=sg-inditex_prices--sb
server.tomcat.threads.max=10
server.port=8081
server.servlet.context-path=/rest/v1

### Config Data Base : JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

### Config Data Base : SQL Initialization (Spring Boot 3.x)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql

### Config Data Base : H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true