-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS ECOMMERCE;

CREATE TABLE ECOMMERCE.BRANDS
(
    BRAND_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_NAME VARCHAR(255)                        NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ECOMMERCE.PRICES
(
    PRICE_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID   BIGINT                              NOT NULL,
    PRODUCT_ID INT                                 NOT NULL,
    PRICE_LIST INT                                 NOT NULL,
    PRIORITY   INT                                 NOT NULL,
    START_DATE TIMESTAMP                           NOT NULL,
    END_DATE   TIMESTAMP                           NOT NULL,
    PRICE      DECIMAL(10, 2)                      NOT NULL,
    CURRENCY   VARCHAR(3)                          NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BRAND_ID) REFERENCES ECOMMERCE.BRANDS (BRAND_ID)
);
