config.log_msg_base_ok=[OK] »
config.log_msg_base_info=[INFO] »
config.log_msg_base_warning=[WARN] »
config.log_msg_base_error=[ERROR] »
config.log_msg_log_formatter={} {} : {}
config.log_msg_date_formatter=yyyy-MM-dd'T'HH:mm:ss.SSSXXX